/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-variant": "#353534",
          "primary-fixed": "#f0dbff",
          "on-background": "#e5e2e1",
          "inverse-on-surface": "#313030",
          "inverse-surface": "#e5e2e1",
          "surface-container-lowest": "#0e0e0e",
          "surface-tint": "#ddb7ff",
          "on-secondary": "#003640",
          "outline": "#988d9f",
          "secondary-fixed": "#acedff",
          "on-primary-fixed-variant": "#6900b3",
          "on-surface-variant": "#cfc2d6",
          "surface-container-low": "#1c1b1b",
          "surface-container-high": "#2a2a2a",
          "on-tertiary-container": "#560038",
          "tertiary-fixed-dim": "#ffafd3",
          "tertiary-fixed": "#ffd8e7",
          "tertiary": "#ffafd3",
          "on-error-container": "#ffdad6",
          "primary-fixed-dim": "#ddb7ff",
          "surface-container-highest": "#353534",
          "on-tertiary-fixed": "#3d0026",
          "primary-container": "#b76dff",
          "primary": "#ddb7ff",
          "on-surface": "#e5e2e1",
          "error": "#ffb4ab",
          "secondary-container": "#03b5d3",
          "on-secondary-fixed": "#001f26",
          "secondary-fixed-dim": "#4cd7f6",
          "error-container": "#93000a",
          "on-tertiary-fixed-variant": "#85145a",
          "on-primary-container": "#400071",
          "inverse-primary": "#842bd2",
          "on-secondary-container": "#00424e",
          "on-primary-fixed": "#2c0051",
          "on-primary": "#490080",
          "surface-container": "#201f1f",
          "secondary": "#4cd7f6",
          "surface-bright": "#3a3939",
          "surface": "#131313",
          "on-error": "#690005",
          "outline-variant": "#4d4354",
          "on-tertiary": "#620040",
          "surface-dim": "#131313",
          "tertiary-container": "#e364a7",
          "background": "#131313",
          "on-secondary-fixed-variant": "#004e5c"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "xs": "4px",
          "safe-area": "20px",
          "md": "24px",
          "xl": "64px",
          "gutter": "16px",
          "base": "8px",
          "sm": "12px",
          "lg": "40px"
      },
      "fontFamily": {
          "display-xl": ["Space Grotesk"],
          "body-lg": ["Inter"],
          "label-sm": ["Inter"],
          "headline-md": ["Space Grotesk"],
          "body-md": ["Inter"],
          "headline-lg": ["Space Grotesk"]
      },
      "fontSize": {
          "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
